export default {
	cn:{
		tabs:{
			index:'新闻',
			my:"我的",
			socirty:'公会',
			special:'专题',
		},
		loading:'正在努力更新',
		loading2:'加载中...',
		loading3:'釋放立即刷新...',
		loading4:'下拉即可刷新...',
		send:'提交',
		index1:'搜索关注的内容',
		index2:'热点新闻',
		index3:'快讯',
		index4:'分享',
		news1:"新闻",
		news2:'小时前',
		news3:"阅读量",
		news4:"举报",
		news5:"推荐阅读",
		news6:"收藏",
		news7:"分享",
		share1:'微信好友',
		share2:'朋友圈',
		share3:'QQ',
		share4:'复制链接',
		share5:'让区块链随处发生',
		report1:'举报',
		report2:'请选择举报原因',
		report3:'垃圾信息',
		report4:'色情',
		report5:'不实信息',
		report6:'垃圾信息',
		report7:'泄露隐私',
		report8:'内容抄袭',
		report9:'违法信息',
		report10:'诈骗信息',
		report11:'其他',
		report12:'举报内容',
		report13:'举报原因',
		report14:'举报描述（字数 16 字以上）',
		search1:"搜索文章、快讯、专题",
		search2:"热门搜索",
		search3:"历史搜索",
		search4:"综合",
		search5:"精选",
		search6:"文章",
		search7:"快讯",
		search8:"专题",
		search9:"个结果",
		search10:"查看更多",
		search11:"搜索",
		search12:"取消",
		search13:"请输入搜索内容",
		
	},
	tc:{
		tabs:{
			index:'新聞',
			my:"我的",
			socirty:'公會',
			special:'專題',
		},
		loading:'正在努力更新',
		loading2:'加载中...',
		loading3:'釋放立即刷新...',
		loading4:'下拉即可刷新...',
		send:'提交',
		index1:'搜索關注的內容',
		index2:'熱點新聞',
		index3:'快訊',
		index4:'分享',
		news1:"新聞",
		news2:'小時前',
		news3:"閱讀量",
		news4:"舉報",
		news5:"推薦閱讀",
		news6:"收藏",
		news7:"分享",
		share1:'微信好友',
		share2:'朋友圈',
		share3:'QQ',
		share4:'複製鏈接',
		share5:'讓區塊鏈隨處發生',
		report1:'舉報',
		report2:'請選擇舉報原因',
		report3:'垃圾信息',
		report4:'色情',
		report5:'不實信息',
		report6:'垃圾信息',
		report7:'泄露隱私',
		report8:'內容抄襲',
		report9:'違法信息',
		report10:'詐騙信息',
		report11:'其他',
		report12:'舉報內容',
		report13:'舉報原因',
		report14:'舉報描述（字數 16 字以上）',
		search1:"搜索文章、快訊、專題",
		search2:"熱門搜索",
		search3:"歷史搜索",
		search4:"綜合",
		search5:"精選",
		search6:"文章",
		search7:"快訊",
		search8:"專題",
		search9:"個結果",
		search10:"查看更多",
		search11:"搜索",
		search12:"取消",
		search13:"請輸入搜索內容",
	},
	en:{
		tabs:{
			index:'news',
			my:"my",
			socirty:'socirty',
			special:'special',
		},
		loading:'Trying to update',
		loading2:'Load...',
		loading3:'Freeze immediately...',
		loading4:'Drop down to refresh...',
		send:'Submission',
		index1:'Search',
		index2:'hot news',
		index3:'express',
		index4:'share',
		news1:"news",
		news2:'Hours Ago',
		news3:"people ",
		news4:"report",
		news5:"Recommended",
		news6:"collection",
		news7:"share",
		share1:'WeChat',
		share2:'Moments',
		share3:'QQ',
		share4:'Copy link',
		share5:'Make Blockchain Happen Everywhere',
		report1:'report',
		report2:'Please select reason to report',
		report3:'spam',
		report4:'pornography',
		report5:'untrue information',
		report6:'spam',
		report7:'eveal privacy',
		report8:'Content plagiarism',
		report9:'Illegal information',
		report10:'Fraud info',
		report11:'other',
		report12:'Report content',
		report13:'Reason for reporting',
		report14:'Report Description (16 words or more)',
		search1:"Search articles, newsletters, features",
		search2:"hot searches",
		search3:"history search",
		search4:"integrated",
		search5:"select",
		search6:"article",
		search7:"express",
		search8:"the project",
		search9:"results",
		search10:"View more",
		search11:"Search",
		search12:"Cancel",
		search13:"Please enter search content",
	}
}