//语言
const lang2 = {
	cn:{
		orePool59:'冻结算力',
		dangjiePower1:'我的矿机',
		dangjiePower2:'升级矿池',
		dangjiePower4:'算力',
		dangjiePower5:'质押数量',
		dangjiePower6:'今日收益(BXB)',
		dangjiePower7:'累计收益(BXB)',
		dangjiePower8:'升级',
		dangjiePower9:'消耗冻结算力',
		// -------------------------------------------
		tibiRecord1:'提币记录',
		tibi1:'提币申请',
		tibi2:'确认提币',
		analysis1:'算力分析',
		analysis2:'总挖矿收益',
		analysis3:'我的总算力',
		analysis4:'锁仓数量',
		analysis5:'可用数量',
		analysis6:'今日收益',
		analysis7:'累计收益',
		analysis8:'释放明细',
		analysis9:'提币申请',
		saveProfit1:'储存收益',
		saveProfit2:'数据分析',
		saveProfit3:'矿机总收益(BXB)',
		saveProfit4:'矿机总算力',
		saveProfit5:'昨日收益(BXB)',
		saveProfit6:'收益明细',
		saveProfit7:'释放空间',
		saveProfit8:'总币数',
		saveProfit9:'实收',
		saveProfit10:'发放时间',
		appForMiningRecord1:'申请记录',
		appForMiningRecord2:'时间',
		appForMiningRecord3:'算力数量(T)',
		appForMiningRecord4:'消费',
		appForMiningRecord5:'状态',
		appForMiningRecord6:'已完成',
		appForMiningRecord6:'待确定',
		appForMiningRecord7:'请输入算力数量',
		appForMiningRecord8:'算力数量不能为0',
		appForMiningRecord9:'BXB余额不足',
		appForMiningRecord10:'USDT余额不足',
		appForMining1:'申请挖矿',
		appForMining2:'算力数量(T)',
		appForMining3:'请输入整数',
		appForMining4:'申请支付额',
		appForMining5:'可用',
		file1:'Fil矿机',
		file2:'储存收益',
		file3:'算力分析',
		file4:'申请挖矿',
		file5:'Filecoin 运营数据',
		file6:'全网总算力',
		file7:'区块难度',
		file8:'BXB总算力',
		file9:'今日产出',
		file10:'交易所 Filecoin 价格',
		file11:'24H最高价',
		file12:'24H最低价',
		file13:'24H成交额',
		// --------------------------------//
		qiang1:"抢购金额",
		qiang2:"到期收益",
		qiang3:"抢购时间",
		qiang4:"到期时间",
		de:'的',
		downPullToRefresh:"下拉即可刷新",
		downReleaseToRefresh:"释放立即刷新",
		downRefreshing:"加载中...",
		contentText:{
			contentdown: '上拉显示更多',
			contentrefresh: '正在加载...',
			contentnomore: '已经到底了'
		},
		day:'天',
		back:'返回',
		Paymentpassword:'资金密码',
		enterthepayment:'请输入资金密码',
		confirm:'确认',
		cancel:'取消',
		Nodataavailable:'暂无数据',
		languageSwitching:'语言切换',
		SimplifiedChinese:'简体中文',
		TraditionalChinese:'繁体中文',
		English:'英文',
		download:'下载 APP',
		download2:'锁仓释放',
		ScanQRcode:'扫二维码',
		Downloadlink:'下载链接',
		Copylink:'复制链接',
		Downloadlinkcopied:'下载链接已复制',
		accounts:'切换钱包',
		Addaccount:'添加钱包',
		Deleteaccount:'删除钱包',
		youwanttodelete:'是否确认删除当前账号',
		Switchedto:'已切换至',
		passwordcannotbeempty:'资金密码不能为空',
		Successfullydeleted:'删除成功',
		Questionfeedback:'问题反馈',
		Plttfquestion:'请选择您要反馈的问题类型',
		Pleasedescribeyourproblem:'请描述您的问题，以便我们尽快为您处理(必填)',
		Submitfeedback:'提交反馈',
		Loginquestions:'登录问题',
		Abnormalfeedback:'异常反馈',
		Functionsuggestion:'功能建议',
		Bugproblem:'BUG问题',
		other:'其他',
		Feedbackcontentcannotbeempty:'反馈内容不能为空',
		Theproblemhasbeenfedback:'问题已反馈',
		Feedbackresults:'反馈结果',
		Processing:'正在处理',
		Myteam:'我的团队',
		Totalteamsize:'团队总人数',
		Totalnumberofdirect:'直推总人数',
		Directpushlist:'直推列表',
		nickname:'昵称',
		Calculationpower:'算力',
		Registrationtime:'注册时间',
		exportMnemonics:'导出助记词',
		pleaseKeepYourMnemonicsProperly:'请妥善保管您的助记词',
		saveToAlbum:'保存至相册',
		savedToAlbum:'已保存至相册',
		failedToSaveMnemonics:'助记词保存失败',
		mnemonicDrawingFailed:'助记词绘制失败',
		exportPrivateKey:'导出私钥',
		keepPrivateKey:'请妥善保管私钥，建议离线保存，物理隔绝，远离网络',
		privateKeyNetworking:'请勿在私钥联网的情况下分享和储存，避免丢失，一旦被 人恶意获取，可能造成不可',
		copyPrivateKey:'复制私钥',
		privateKeyCopied:'私钥已复制',
		securityCenter:'安全中心',
		changePaymentPassword:'修改资金密码',
		findThePaymentPassword:'找回资金密码',
		paymentPasswordVerificationRequired:'需要资金密码验证',
		pleaseEnterThePaymentPassword:'请输入资金密码',
		paymentPasswordModification:'资金密码修改',
		oldPaymentPassword:'旧资金密码',
		pleaseEnterTheOldPassword:'请输入旧密码',
		newPaymentPassword:'新资金密码',
		pleaseEnterANewPassword:'请输入新密码',
		confirmNewPassword:'确认新密码',
		pleaseEnterTheNewPasswordAgain:'请再次输入新密码',
		Submit:'提交',
		oldPaymentPasswordCannotBeEmpty:'旧资金密码不能为空',
		newPaymentPasswordCannotBeEmpty:'新资金密码不能为空',
		theNewPasswordEnteredTwiceIsNotTheSame:'两次输入的新密码不相同',
		paymentPasswordModifiedSuccessfully:'资金密码修改成功',
		paymentPasswordRecovery:'资金密码找回',
		pleaseEnterAMnemonicOrPrivateKey:'请输入助记词或私钥（助记词英文单词请用空格分隔）',
		mnemonicWordsCannotBeEmpty:'助记词不能为空',
		paymentPasswordSetSuccessfully:'资金密码设置成功',
		my1:'我的邀请码',
		my2:'邀请码已复制',
		assets1:'资金净资产',
		assets2:'充值',
		assets3:'提现',
		assets4:'资产划转',
		assets5:'内部转账',
		assets6:'币种',
		assets7:'可用',
		assets8:'冻结',
		assets9:[
			{
				name: "资金主页"
			}, {
				name: "矿池钱包"
			}
		],
		assets10:'划转记录',
		fundsTransfer1:'划转币种',
		fundsTransfer2:'请选择币种',
		fundsTransfer3:'从',
		fundsTransfer4:'划转数量',
		fundsTransfer5:'请输入数量',
		fundsTransfer6:'可用数量',
		fundsTransfer7:'全部填入',
		fundsTransfer8:'手续费',
		fundsTransfer8Tip:'BXB手续费将会进入黑洞',
		fundsTransfer8Tip2:'提示',
		fundsTransfer9xiaohao:'消耗',
		fundsTransfer9:'实际到账',
		fundsTransfer10:'划转选择',
		fundsTransfer11:'操作中...',
		fundsTransfer12:'不可划转到相同钱包',
		fundsTransfer13:'划转数量不能为空',
		fundsTransfer14:'划转数量不能为0',
		fundsTransfer15:'划转数量不能大于可用数量',
		fundsTransfer16:'划转成功',
		fundsTransfer17:'到',
		fundsTransfer18:[
			{
				name:'资产钱包',
				value:0
			},
			{
				name:'矿池钱包',
				value:1
			},
			{
				name:'酿酒计划',
				value:2
			},
			{
				name:'商城钱包',
				value:3
			}
		],
		transfer1:'转账币种',
		transfer2:'用户昵称',
		transfer3:'请输入用户昵称',
		transfer4:'转账数量',
		transfer5:'全部',
		transfer6:'用户昵称不能为空',
		transfer7:'转账数量不能为空',
		transfer8:'转账数量不能为0',
		transfer9:'转账数量不能大于可用数量',
		transfer10:'操作成功',
		transfer11:'转账记录',
		transfer12:'转账',
		transfer13:'给',
		transfer14:'转入',
		businessSchool1:'商学院',
		businessSchool2:'官方资料',
		businessSchool3:'视频集',
		businessSchool4:'PPT课件',
		businessSchool5:'B·X·B 课堂',
		businessSchool6:'专题讲座',
		businessSchool7:'下载中',
		businessSchool8:'取消下载',
		orePool1b:'最佳持币区',
		orePoolh1:'黑洞燃烧',
		orePoolh133:'分红算力',
		orePool1:'矿池',
		orePool2:'矿池总算力',
		orePool3:'硬顶池总额',
		orePool4:'每日签到释放',
		orePool5:'已签到',
		orePool6:'签到',
		orePool7:'算力',
		orePool8:'矿池余额',
		orePool9:'分红矿池',
		orePool10:'累计收益',
		orePool11:'挖矿矿池',
		orePool12:'奖励明细',
		orePool13:'释放明细',
		orePool14:'我的矿池',
		orePool142:'矿池收益',
		orePool15:'矿机列表',
		orePool16:'奖励',
		orePool17:'开启挖矿',
		orePool18:'已开启',
		orePool19:'签到成功',
		orePool20:'矿池详情',
		orePool21:'总挖矿量',
		orePool22:'钱包数',
		orePoolt22:'我的动1系数',
		orePoolc22:'团队算力',
		orePool23:'我的动2系数',
		orePool24:'团队算力',
		orePool25:'累计待挖',
		orePool26:'我的算力',
		orePool27:'全网算力',
		orePool28:'我要赎回',
		orePool28back:'天后可赎回',
		orePool29:'质押数量',
		orePool30:'今日收益',
		orePool31:'你将赎回',
		orePool32:'的手续费',
		orePool33:'平台将收取',
		orePool34:'确认赎回',
		orePool35:'矿池赎回成功',
		orePool36:'开启矿池',
		orePool37:'算力价格',
		orePool38:'价格',
		orePool39:'支付额',
		orePool40:'确认入驻',
		orePool41:'矿池开启成功',
		orePool42:'矿池价格',
		orePool43:'释放总数',
		orePool44:'今日预计释放',
		orePool45:'释放数量',
		orePool46:'奖励累计',
		orePool47:'今日奖励',
		orePool48:'奖励数量',
		orePool49:'矿池收益',
		orePool50:'普通矿池',
		orePool51:'最佳矿池',
		orePool52:'提取',
		orePool53:'已提取',
		orePool54:'投入的BXB数量',
		orePool60:'算力',
		orePool55:'收益',
		orePool56:'硬顶',
		orePool57:'提取成功',
		orePool58:'提取失败',
		recharge1:'充值币种',
		recharge2:'充币地址',
		recharge3:'复制地址',
		recharge4:'请勿向上述地址充值任何非USDT资产，否则资产将不可找回。',
		recharge5:'最小充值金额：1 USDT，小于最小金额的充值将不会上账且无法退回。',
		recharge6:'您的充值地址不会经常改变，可以重复充值；如果更改，我们会尽量通过网站公告或邮件通知您。',
		recharge7:'充币地址已复制',
		recharge8:'充值记录',
		rushGame1:'预约记录',
		rushGame2:'抢购记录',
		rushGame3:'我的红酒',
		rushGame4:'交易明细',
		rushGame5:'分红明细',
		rushGame6:'需要燃料',
		rushGame7:'抢购时间',
		rushGame8:'合约收益',
		rushGame9:'酿造中',
		rushGame10:'可抢购',
		rushGame102:'预约中',
		rushGame11:'资产',
		rushGame12:'冻结资产',
		rushGame13:'累计释放',
		rushGame14:'可用资产',
		rushGame15:'托单资产',
		rushGame16:'分红池详情',
		rushGame17:'分红池',
		rushGame18:'钱包数',
		rushGame19:'累计待分红',
		rushGame20:'预约需要支付价值',
		rushGame21:'燃料',
		rushGame22:'抢购失败将会退回',
		rushGame23:'确认预约',
		rushGame25:[{
			name: "酿酒计划"
		}, {
			name: "酿酒资产"
		}, {
			name: "返回首页",
			disabled: true
		}],
		rushGame26:'抢购成功',
		rushGame27:'抢购中',
		rushGame28:'未抢到',
		rushGame29:'转让中',
		rushGame30:'闲置中',
		rushGame31:'确认支付',
		// rushGame32:[{
		// 	name: "全部"
		// }, {
		// 	name: "闲置中"
		// }, {
		// 	name: "转让中",
		// }],
		rushGame32:[ {
			name: "收益中"
		},{
			name: "闲置中"
		}, {
			name: "转让中",
		}],
		rushGame33:'待支付',
		rushGame34:'已完成',
		rushGame35:'支付成功',
		rushGame36:[{
			name: "全部"
		}, {
			name: "待支付"
		}, {
			name: "已成交",
		}],
		withdrawal1:'提现',
		withdrawal2:'提币币种',
		withdrawal3:'提币地址',
		withdrawal4:'请输入地址',
		withdrawal5:'提币数量',
		withdrawal6:'请输入提币数量',
		withdrawal7:'扫码出错',
		withdrawal8:'提币地址不能为空',
		withdrawal9:'提币数量不能为空',
		withdrawal10:'提币数量不能为0',
		withdrawal11:'提币数量不能大于可用数量',
		withdrawal12:'提现记录',
		withdrawal13:'提币',
		withdrawal14:'提币成功',
		withdrawal15:'提币失败',
		withdrawal16:'提币中',
		withdrawal17:'申请中',
		xiaofeiyue:'消费余额',
	},
	us:{
		tibiRecord1:'Withdrawal record',
		tibi1:'Withdrawal application',
		tibi2:'Confirm',
		analysis1:'Analysis',
		analysis2:'Total mining revenue',
		analysis3:'My total strength',
		analysis4:'Lock',
		analysis5:'Available',
		analysis6:'Today`s earnings',
		analysis7:'Cumulative',
		analysis8:'Release details',
		analysis9:'Withdrawal application',
		saveProfit1:'Withdrawal application',
		saveProfit2:'Data analysis',
		saveProfit3:'Total revenue of mining machinery(BXB)',
		saveProfit4:'The total calculation power of mining machine',
		saveProfit5:'Yesterday`s earnings(BXB)',
		saveProfit6:'Income details',
		saveProfit7:'Free space',
		saveProfit8:'Total currency',
		saveProfit9:'net receipts',
		saveProfit10:'time',
		appForMiningRecord1:'Application record',
		appForMiningRecord2:'time',
		appForMiningRecord3:'Calculation quantity(T)',
		appForMiningRecord4:'consumption',
		appForMiningRecord5:'state',
		appForMiningRecord6:'Completed',
		appForMiningRecord6:'To be determined',
		appForMiningRecord7:'Please input the quantity of calculation force',
		appForMiningRecord8:'Force quantity cannot be 0',
		appForMiningRecord9:'Insufficient BXB balance',
		appForMiningRecord10:'Insufficient USDT balance',
		appForMining1:'Application for mining',
		appForMining2:'Calculation quantity(T)',
		appForMining3:'please enter an integer',
		appForMining4:'Applied payment',
		appForMining5:'available',
		file1:'Fil miner',
		file2:'Storage income',
		file3:'Calculation force analysis',
		file4:'Application for mining',
		file5:'Filecoin Operation data',
		file6:'Total power',
		file7:'Block difficulty',
		file8:'BXB final strength',
		file9:'Output today',
		file10:'Exchange Filecoin Price',
		file11:'H',
		file12:'L',
		file13:'V',
		qiang1:"Rush amount",
		qiang2:"Income at maturity",
		qiang3:"Rush time",
		qiang4:"Due date",
		de:'Of',
		downPullToRefresh:"Drop down to refresh",
		downReleaseToRefresh:"Release refresh now",
		downRefreshing:"Loading...",
		contentText:{
			contentdown: 'Pull up to show more',
			contentrefresh: 'Loading...',
			contentnomore: 'End'
		},
		day:'Day',
		back:'Back',
		Paymentpassword:'Payment password',
		enterthepayment:'Please enter the payment password',
		confirm:'Confirm',
		cancel:'Cancel',
		Nodataavailable:'No data available',
		languageSwitching:'Language switching',
		SimplifiedChinese:'Simplified Chinese',
		TraditionalChinese:'Traditional Chinese',
		English:'English',
		download:'Download App',
		download2:'Lock up',
		ScanQRcode:'Scan QR Code',
		Downloadlink:'Download link',
		Copylink:'Copy link',
		Downloadlinkcopied:'Download link copied',
		accounts:'Switch wallets',
		Addaccount:'Add Wallet',
		Deleteaccount:'Delete Wallet',
		youwanttodelete:'Are you sure you want to delete the current account',
		Switchedto:'Switched to',
		passwordcannotbeempty:'Payment password cannot be empty',
		Successfullydeleted:'Successfully deleted',
		Questionfeedback:'Question feedback',
		Plttfquestion:'Please select the type of question you want to feedback',
		Pleasedescribeyourproblem:'Please describe your problem so that we can deal with it for you as soon as possible (required)',
		Submitfeedback:'Submit feedback',
		Loginquestions:'Login questions',
		Abnormalfeedback:'Abnormal feedback',
		Functionsuggestion:'Function suggestion',
		Bugproblem:'Bug problem',
		other:'other',
		Feedbackcontentcannotbeempty:'Feedback content cannot be empty',
		Theproblemhasbeenfedback:'The problem has been fed back',
		Feedbackresults:'Feedback results',
		Processing:'Processing',
		Myteam:'My team',
		Totalteamsize:'Total team size',
		Totalnumberofdirect:'Total number of direct push',
		Directpushlist:'Direct push list',
		nickname:'nickname',
		Calculationpower:'Calculation power',
		Registrationtime:'Registration time',
		exportMnemonics:'Export mnemonics',
		pleaseKeepYourMnemonicsProperly:'Please keep your mnemonics properly',
		saveToAlbum:'Save',
		savedToAlbum:'Saved to album',
		failedToSaveMnemonics:'Failed to save mnemonics',
		mnemonicDrawingFailed:'Mnemonic drawing failed',
		exportPrivateKey:'Export private key',
		keepPrivateKey:'Please keep the private key properly. It is recommended to keep it offline, physically isolated and away from the network',
		privateKeyNetworking:'Please do not share and store the private key in the case of networking to avoid loss. Once it is obtained maliciously, it may cause irresistible loss',
		copyPrivateKey:'Copy',
		privateKeyCopied:'Private key copied',
		securityCenter:'Security Center',
		changePaymentPassword:'Change payment password',
		findThePaymentPassword:'Find the payment password',
		paymentPasswordVerificationRequired:'Payment password verification required',
		pleaseEnterThePaymentPassword:'Please enter the payment password',
		paymentPasswordModification:'Change password',
		oldPaymentPassword:'Old payment password',
		pleaseEnterTheOldPassword:'Please enter the old password',
		newPaymentPassword:'New payment password',
		pleaseEnterANewPassword:'Please enter a new password',
		confirmNewPassword:'Confirm new password',
		pleaseEnterTheNewPasswordAgain:'Please enter the new password again',
		Submit:'Submit',
		oldPaymentPasswordCannotBeEmpty:'Old payment password cannot be empty',
		newPaymentPasswordCannotBeEmpty:'New payment password cannot be empty',
		pleaseEnterTheNewPasswordAgain:'Please enter the new password again',
		theNewPasswordEnteredTwiceIsNotTheSame:'The new password entered twice is not the same',
		paymentPasswordModifiedSuccessfully:'Payment password modified successfully',
		paymentPasswordRecovery:'Password recovery',
		pleaseEnterAMnemonicOrPrivateKey:'Please input mnemonic words or private key to retrieve payment password',
		mnemonicWordsCannotBeEmpty:'Mnemonic words cannot be empty',
		paymentPasswordSetSuccessfully:'Payment password set successfully',
		my1:'My invitation code',
		my2:'Invitation code copied',
		assets1:'Net capital assets',
		assets2:'Recharge',
		assets3:'Withdrawal',
		assets4:'Transfer of assets',
		assets5:'Internal transfer',
		assets6:'Currency',
		assets7:'Available',
		assets8:'Frozen',
		assets9:[
			{
				name: "Capital"
			}, {
				name: "Ore pool"
			}
		],
		assets10:'Transfer record',
		fundsTransfer1:'Transfer currency',
		fundsTransfer2:'Please select currency',
		fundsTransfer3:'from',
		fundsTransfer4:'Transferred quantity',
		fundsTransfer5:'Please input quantity',
		fundsTransfer6:'Available quantity',
		fundsTransfer7:'Fill in all',
		fundsTransfer8:'Service Charge',
		fundsTransfer8Tip:'BXB Fees will go into the black hole',
		fundsTransfer8Tip2:'Tips',
		fundsTransfer9xiaohao:'consume',
		fundsTransfer9:'Actual arrival',
		fundsTransfer10:'Transfer options',
		fundsTransfer11:'In operation...',
		fundsTransfer12:'Do not transfer to the same wallet',
		fundsTransfer13:'Transfer quantity cannot be empty',
		fundsTransfer14:'Transfer quantity cannot be 0',
		fundsTransfer15:'Transfer quantity cannot be greater than available quantity',
		fundsTransfer16:'Successful transfer',
		fundsTransfer17:'To',
		fundsTransfer18:[
			{
				name:'Asset Wallet',
				value:0
			},
			{
				name:'Pool Wallet',
				value:1
			},
			{
				name:'Brew Plan',
				value:2
			},
			{
				name:'Mall Wallet',
				value:3
			}
		],
		transfer1:'Transfer currency',
		transfer2:'User nickname',
		transfer3:'Please enter user nickname',
		transfer4:'Transfer quantity',
		transfer5:'Full',
		transfer6:'User nickname cannot be empty',
		transfer7:'Transfer quantity cannot be empty',
		transfer8:'Transfer quantity cannot be 0',
		transfer9:'Transfer quantity cannot be greater than available quantity',
		transfer10:'Operation successful',
		transfer11:'Transfer record',
		transfer12:'Transfer',
		transfer13:'To',
		transfer14:'In',
		businessSchool1:'Business School',
		businessSchool2:'Official information',
		businessSchool3:'Video collection',
		businessSchool4:'PPT courseware',
		businessSchool5:'B·X·B class',
		businessSchool6:'Special lecture',
		businessSchool7:'Downloading',
		businessSchool8:'Cancel Download',
		orePool1b:'Best holding',
		orePoolh1:"Black",
		orePoolh133:'Bonus Power',
		orePool1:'Ore pool',
		orePool2:'Total capacity of ore pool',
		orePool3:'Total amount of hardtop pool',
		orePool4:'Daily check in and release',
		orePool5:'Signed in',
		orePool6:'Sign in',
		orePool7:'Calculation power',
		orePool8:'Pool balance',
		orePool9:'Dividend pool',
		orePool10:'Cumulative revenue',
		orePool11:'Mining pond',
		orePool12:'Award details',
		orePool13:'Release details',
		orePool14:'My mine',
		orePool142:'Pool income',
		orePool15:'List of mining machines',
		orePool16:'reward',
		orePool17:'Start mining',
		orePool18:'Turned on',
		orePool19:'Successful sign in',
		orePool20:'Pool details',
		orePool21:'Total mining volume',
		orePool22:'Number of wallets',
		orePoolt22:'My dynamic 1 coefficient',
		orePoolc22:'Team power',
		orePool23:'My dynamic 2 coefficient',
		orePool24:'Team computing power',
		orePool25:'Accumulated to be excavated',
		orePool26:'My computing power',
		orePool27:'Network computing power',
		orePool28:'Redeem',
		orePool28back:'days redeem',
		orePool29:'Pledge quantity',
		orePool30:'Today`s earnings',
		orePool31:'You will redeem it',
		orePool32:'Service Charge',
		orePool33:'The platform will charge',
		orePool34:'Confirmation of redemption',
		orePool35:'Successful redemption of ore pool',
		orePool36:'Open the pit',
		orePool37:'Power price',
		orePool38:'Price',
		orePool39:'Payment amount',
		orePool40:'Confirm entry',
		orePool41:'Mine pool opened successfully',
		orePool42:'Pool price',
		orePool43:'Total number of releases',
		orePool44:'The release is expected today',
		orePool45:'Number of releases',
		orePool46:'Bonus accumulation',
		orePool47:'Award today',
		orePool48:'Number of awards',
		orePool49:'Pool income',
		orePool50:'Ordinary',
		orePool51:'Optimum',
		orePool52:'Extract',
		orePool53:'Extracted',
		orePool54:'Committed BXB',
		orePool60:'power',
		orePool55:'Profit',
		orePool56:'Hardtop',
		orePool57:'Extraction successful',
		orePool58:'Extraction failed',
		recharge1:'Recharge currency',
		recharge2:'Charging address',
		recharge3:'Copy address',
		recharge4:'Please do not recharge any non usdt assets to the above address, otherwise the assets will not be retrieved.。',
		recharge5:'Minimum recharge amount: 1 usdt. Recharge less than the minimum amount will not be recorded and cannot be returned.',
		recharge6:'Your recharge address will not change frequently, you can recharge repeatedly; if you change, we will try our best to inform you through website announcement or email.',
		recharge7:'Charge address copied',
		recharge8:'Recharge record',
		rushGame1:'Appointment record',
		rushGame2:'Rush purchase record',
		rushGame3:'My red wine',
		rushGame4:'Transaction details',
		rushGame5:'Dividend details',
		rushGame6:'Fuel',
		rushGame7:'Time',
		rushGame8:'Income',
		rushGame9:'Brewing',
		rushGame10:'Snap up',
		rushGame102:'Reserve',
		rushGame11:' Assets',
		rushGame12:'Freezing assets',
		rushGame13:'Cumulative release',
		rushGame14:'Available assets',
		rushGame15:'Entrusted assets',
		rushGame16:'Dividend pool details',
		rushGame17:'Dividend pool',
		rushGame18:'Wallets',
		rushGame19:'Bonus',
		rushGame20:'Booking needs to pay value',
		rushGame21:'Fuel',
		rushGame22:'Failure of rush purchase will be returned',
		rushGame23:'Confirm appointment',
		rushGame25:[{
			name: "Brew Plan"
		}, {
			name: "Assets"
		}, {
			name: "Back",
			disabled: true
		}],
		rushGame26:'Successful',
		rushGame27:'Buying',
		rushGame28:'Lose',
		rushGame29:'Transfer',
		rushGame30:'Free',
		rushGame31:'Confirm payment',
		// rushGame32:[{
		// 	name: "Whole"
		// }, {
		// 	name: "Free"
		// }, {
		// 	name: "Transfer",
		// }],
		rushGame32:[{
			name: "Revenue"
		}, {
			name: "Free"
		},{
			name: "Transfer",
		}],
		rushGame33:'To be paid',
		rushGame34:'Completed',
		rushGame35:'Payment successful',
		rushGame36:[{
			name: "Whole"
		}, {
			name: "Payment"
		}, {
			name: "Completed",
		}],
		withdrawal1:'Withdrawal',
		withdrawal2:'Withdrawal currency',
		withdrawal3:'Withdrawal address',
		withdrawal4:'Please enter the address',
		withdrawal5:'Withdrawal quantity',
		withdrawal6:'Please input the withdrawal quantity',
		withdrawal7:'Error scanning code',
		withdrawal8:'Withdrawal address cannot be empty',
		withdrawal9:'Withdrawal quantity cannot be empty',
		withdrawal10:'Withdrawal quantity cannot be 0',
		withdrawal11:'The withdrawal quantity cannot be greater than the available quantity',
		withdrawal12:'Withdrawal record',
		withdrawal13:'Withdraw',
		withdrawal14:'Withdraw successfully',
		withdrawal15:'Failed to withdraw',
		withdrawal16:'Withdrawal in progress',
		withdrawal17:'Application in progress',
		xiaofeiyue:'Balance',
	},
	tw:{
		tibiRecord1:'提幣記錄',
		tibi1:'提幣申請',
		tibi2:'確認提幣',
		analysis1:'算力分析',
		analysis2:'總挖礦收益',
		analysis3:'我的總算力',
		analysis4:'鎖倉數量',
		analysis5:'可用數量',
		analysis6:'今日收益',
		analysis7:'累計收益',
		analysis8:'釋放明細',
		analysis9:'提幣申請',
		saveProfit1:'儲存收益',
		saveProfit2:'資料分析',
		saveProfit3:'礦機總收益（BXB）',
		saveProfit4:'礦機總算力',
		saveProfit5:'昨日收益（BXB）',
		saveProfit6:'收益明細',
		saveProfit7:'釋放空間',
		saveProfit8:'總幣數',
		saveProfit9:'實收',
		saveProfit10:'發放時間',
		appForMiningRecord1:'申請記錄',
		appForMiningRecord2:'時間',
		appForMiningRecord3:'算力數量（T）',
		appForMiningRecord4:'消費',
		appForMiningRecord5:'狀態',
		appForMiningRecord6:'已完成',
		appForMiningRecord6:'待確定',
		appForMiningRecord7:'請輸入算力數量',
		appForMiningRecord8:'算力數量不能為0',
		appForMiningRecord9:'BXB餘額不足',
		appForMiningRecord10:'USDT餘額不足',
		appForMining1:'申請挖礦',
		appForMining2:'算力數量（T）',
		appForMining3:'请输入整数',
		appForMining4:'請輸入整數',
		appForMining5:'可用',
		file1:'Fil礦機',
		file2:'儲存收益',
		file3:'算力分析',
		file4:'申請挖礦',
		file5:'Filecoin運營數據',
		file6:'全網總算力',
		file7:'區塊難度',
		file8:'BXB總算力',
		file9:'今日產出',
		file10:'交易所Filecoin價格',
		file11:'24H最高價',
		file12:'24H最低價',
		file13:'24H成交額',
		qiang1:"搶購金額",
		qiang2:"到期收益",
		qiang3:"搶購時間",
		qiang4:"到期時間",
		de:'的',
		downPullToRefresh:"下拉即可重繪",
		downReleaseToRefresh:"釋放立即重繪",
		downRefreshing:"加載中...",
		contentText:{
			contentdown: '上拉顯示更多',
			contentrefresh: '正在加載...',
			contentnomore: '已經到底了'
		},
		day:'天',
		back:'返回',
		Paymentpassword:'資金密碼',
		enterthepayment:'請輸入資金密碼',
		confirm:'確認',
		cancel:'取消',
		Nodataavailable:'暫無數據',
		languageSwitching:'語言切換',
		SimplifiedChinese:'簡體中文',
		TraditionalChinese:'繁體中文',
		English:'英文',
		download:'下載 APP',
		download2:'锁仓释放',
		ScanQRcode:'掃二維碼',
		Downloadlink:'下載連結',
		Copylink:'複製連結',
		Downloadlinkcopied:'下載連結已複製',
		accounts:'切換錢包',
		Addaccount:'添加錢包',
		Deleteaccount:'删除錢包',
		youwanttodelete:'是否確認删除當前帳號',
		Switchedto:'已切換至',
		passwordcannotbeempty:'資金密碼不能為空',
		Successfullydeleted:'删除成功',
		Questionfeedback:'問題迴響',
		Plttfquestion:'請選擇您要迴響的問題類型',
		Pleasedescribeyourproblem:'請描述您的問題，以便我們儘快為您處理(必填)',
		Submitfeedback:'提交迴響',
		Loginquestions:'登入問題',
		Abnormalfeedback:'异常迴響',
		Functionsuggestion:'功能建議',
		Bugproblem:'BUG問題',
		other:'其他',
		Feedbackcontentcannotbeempty:'迴響內容不能為空',
		Theproblemhasbeenfedback:'問題已迴響',
		Feedbackresults:'迴響結果',
		Processing:'正在處理',
		Myteam:'我的團隊',
		Totalteamsize:'團隊總人數',
		Totalnumberofdirect:'直推總人數',
		Directpushlist:'直推清單',
		nickname:'昵稱',
		Calculationpower:'算力',
		Registrationtime:'註冊時間',
		exportMnemonics:'匯出助記詞',
		pleaseKeepYourMnemonicsProperly:'請妥善保管您的助記詞',
		saveToAlbum:'保存至相册',
		savedToAlbum:'已保存至相册',
		failedToSaveMnemonics:'助記詞保存失敗',
		mnemonicDrawingFailed:'助記詞繪製失敗',
		exportPrivateKey:'匯出私密金鑰',
		keepPrivateKey:'請妥善保管私密金鑰，建議離線保存，物理隔絕，遠離網絡',
		privateKeyNetworking:'請勿在私密金鑰聯網的情况下分享和儲存，避免遺失，一旦被 人惡意獲取，可能造成不可',
		copyPrivateKey:'複製私密金鑰',
		privateKeyCopied:'私密金鑰已複製',
		securityCenter:'安全中心',
		changePaymentPassword:'修改資金密碼',
		findThePaymentPassword:'找回資金密碼',
		paymentPasswordVerificationRequired:'需要資金密碼驗證',
		pleaseEnterThePaymentPassword:'請輸入資金密碼',
		paymentPasswordModification:'資金密碼修改',
		oldPaymentPassword:'舊資金密碼',
		pleaseEnterTheOldPassword:'請輸入舊密碼',
		newPaymentPassword:'新資金密碼',
		pleaseEnterANewPassword:'請輸入新密碼',
		confirmNewPassword:'確認新密碼',
		pleaseEnterTheNewPasswordAgain:'請再次輸入新密碼',
		Submit:'提交',
		oldPaymentPasswordCannotBeEmpty:'舊資金密碼不能為空',
		newPaymentPasswordCannotBeEmpty:'新資金密碼不能為空',
		theNewPasswordEnteredTwiceIsNotTheSame:'兩次輸入的新密碼不相同',
		paymentPasswordModifiedSuccessfully:'資金密碼修改成功',
		paymentPasswordRecovery:'資金密碼找回',
		pleaseEnterAMnemonicOrPrivateKey:'請輸入助記詞或私密金鑰（助記詞英文單詞請用空格分隔）',
		mnemonicWordsCannotBeEmpty:'助記詞不能為空',
		paymentPasswordSetSuccessfully:'資金密碼設定成功',
		my1:'我的邀請碼',
		my2:'邀請碼已複製',
		assets1:'資金淨資產',
		assets2:'充值',
		assets3:'提現',
		assets4:'資產劃轉',
		assets5:'內部轉帳',
		assets6:'幣種',
		assets7:'可用',
		assets8:'凍結',
		assets9:[
			{
				name: "資金主頁"
			}, {
				name: "礦池錢包"
			}
		],
		assets10:'劃轉記錄',
		fundsTransfer1:'劃轉幣種',
		fundsTransfer2:'請選擇幣種',
		fundsTransfer3:'從',
		fundsTransfer4:'劃轉數量',
		fundsTransfer5:'請輸入數量',
		fundsTransfer6:'可用數量',
		fundsTransfer7:'全部填入',
		fundsTransfer8:'手續費',
		fundsTransfer8Tip:'BXB 手續費將會進入黑洞',
		fundsTransfer8Tip2:'提示',
		fundsTransfer9xiaohao:'消耗',
		fundsTransfer9:'實際到賬',
		fundsTransfer10:'劃轉選擇',
		fundsTransfer11:'操作中...',
		fundsTransfer12:'不可劃轉到相同錢包',
		fundsTransfer13:'劃轉數量不能為空',
		fundsTransfer14:'劃轉數量不能為0',
		fundsTransfer15:'劃轉數量不能大於可用數量',
		fundsTransfer16:'劃轉成功',
		fundsTransfer17:'到',
		fundsTransfer18:[
			{
				name:'資產錢包',
				value:0
			},
			{
				name:'礦池錢包',
				value:1
			},
			{
				name:'釀酒計畫',
				value:2
			},
			{
				name:'商城錢包',
				value:3
			}
		],
		transfer1:'轉帳幣種',
		transfer2:'用戶昵稱',
		transfer3:'請輸入用戶昵稱',
		transfer4:'轉帳數量',
		transfer5:'全部',
		transfer6:'用戶昵稱不能為空',
		transfer7:'轉帳數量不能為空',
		transfer8:'轉帳數量不能為0',
		transfer9:'轉帳數量不能大於可用數量',
		transfer10:'操作成功',
		transfer11:'轉帳記錄',
		transfer12:'轉帳',
		transfer13:'給',
		transfer14:'轉入',
		businessSchool1:'商學院',
		businessSchool2:'官方資料',
		businessSchool3:'視頻集',
		businessSchool4:'PPT課件',
		businessSchool5:'B·X·B 課堂',
		businessSchool6:'專題講座',
		businessSchool7:'下載中',
		businessSchool8:'取消下載',
		orePool1b:'最佳持幣區',
		orePoolh1:'黑洞燃燒',
		orePoolh133:'分紅算力',
		orePool1:'礦池',
		orePool2:'礦池總算力',
		orePool3:'硬頂池總額',
		orePool4:'每日簽到釋放',
		orePool5:'已簽到',
		orePool6:'簽到',
		orePool7:'算力',
		orePool8:'礦池餘額',
		orePool9:'分紅礦池',
		orePool10:'累計收益',
		orePool11:'挖礦礦池',
		orePool12:'獎勵明細',
		orePool13:'釋放明細',
		orePool14:'我的礦池',
		orePool142:'礦池收益',
		orePool15:'礦機清單',
		orePool16:'獎勵',
		orePool17:'開啟挖礦',
		orePool18:'已開啟',
		orePool19:'簽到成功',
		orePool20:'礦池詳情',
		orePool21:'總挖礦量',
		orePool22:'錢包數',
		orePoolt22:'我的動1係數',
		orePoolc22:'團隊算力',
		orePool23:'我的動2係數',
		orePool24:'團隊算力',
		orePool25:'累計待挖',
		orePool26:'我的算力',
		orePool27:'全網算力',
		orePool28:'我要贖回',
		orePool28back:'天后可贖回',
		orePool29:'質押數量',
		orePool30:'今日收益',
		orePool31:'你將贖回',
		orePool32:'的手續費',
		orePool33:'平臺將收取',
		orePool34:'確認贖回',
		orePool35:'礦池贖回成功',
		orePool36:'開啟礦池',
		orePool37:'算力價格',
		orePool38:'價格',
		orePool39:'支付額',
		orePool40:'確認入駐',
		orePool41:'礦池開啟成功',
		orePool42:'礦池價格',
		orePool43:'釋放總數',
		orePool44:'今日預計釋放',
		orePool45:'釋放數量',
		orePool46:'獎勵累計',
		orePool47:'今日獎勵',
		orePool48:'獎勵數量',
		orePool49:'礦池收益',
		orePool50:'普通礦池',
		orePool51:'最佳礦池',
		orePool52:'選取',
		orePool53:'已選取',
		orePool54:'投入的BXB數量',
		orePool60:'算力',
		orePool55:'收益',
		orePool56:'硬頂',
		orePool57:'選取成功',
		orePool58:'選取失敗',
		recharge1:'充值幣種',
		recharge2:'充幣地址',
		recharge3:'複製地址',
		recharge4:'請勿向上述地址充值任何非USDT資產，否则資產将不可找回。',
		recharge5:'最小充值金額：1 USDT，小於最小金額的充值將不會上帳且無法退回。',
		recharge6:'您的充值地址不會經常改變，可以重複充值；如果更改，我們會儘量通過網站公告或郵件通知您。',
		recharge7:'充幣地址已複製',
		recharge8:'充值記錄',
		rushGame1:'預約記錄',
		rushGame2:'搶購記錄',
		rushGame3:'我的紅酒',
		rushGame4:'交易明細',
		rushGame5:'分紅明細',
		rushGame6:'需要燃料',
		rushGame7:'搶購時間',
		rushGame8:'合約收益',
		rushGame9:'釀造中',
		rushGame10:'可搶購',
		rushGame102:'預約中',
		rushGame11:'資產',
		rushGame12:'凍結資產',
		rushGame13:'累計釋放',
		rushGame14:'可用資產',
		rushGame15:'托單資產',
		rushGame16:'分紅池詳情',
		rushGame17:'分紅池',
		rushGame18:'錢包數',
		rushGame19:'累計待分紅',
		rushGame20:'預約需要支付價值',
		rushGame21:'燃料',
		rushGame22:'搶購失敗將會退回',
		rushGame23:'確認預約',
		rushGame25:[{
			name: "釀酒計畫"
		}, {
			name: "釀酒資產"
		}, {
			name: "返回首頁",
			disabled: true
		}],
		rushGame26:'搶購成功',
		rushGame27:'搶購中',
		rushGame28:'未搶到',
		rushGame29:'轉讓中',
		rushGame30:'閒置中',
		rushGame31:'確認支付',
		// rushGame32:[{
		// 	name: "全部"
		// }, {
		// 	name: "閒置中"
		// }, {
		// 	name: "轉讓中",
		// }],
		rushGame32:[{
			name: "收益中"
		}, {
			name: "閒置中"
		},{
			name: "轉讓中",
		}],
		rushGame33:'待支付',
		rushGame34:'已完成',
		rushGame35:'支付成功',
		rushGame36:[{
			name: "全部"
		}, {
			name: "待支付"
		}, {
			name: "已成交",
		}],
		withdrawal1:'提現',
		withdrawal2:'提幣幣種',
		withdrawal3:'提幣地址',
		withdrawal4:'請輸入地址',
		withdrawal5:'提幣數量',
		withdrawal6:'請輸入提幣數量',
		withdrawal7:'掃碼出錯',
		withdrawal8:'提幣地址不能為空',
		withdrawal9:'提幣數量不能為空',
		withdrawal10:'提幣數量不能為0',
		withdrawal11:'提幣數量不能大於可用數量',
		withdrawal12:'提現記錄',
		withdrawal13:'提幣',
		withdrawal14:'提幣成功',
		withdrawal15:'提幣失敗',
		withdrawal16:'提幣中',
		withdrawal17:'申請中',
		xiaofeiyue:'消費餘額',
    },
}
 export default {
 	lang2
 }